int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int);
void evis_george(void);
void kings_back(void);
void add(int, int);
void print_time_table(int n);
